### ISSUE TITLE
Error while fetching results: java.util.concurrent.TimeoutException: Futures timed out after [5 seconds]

### ISSUE THREAD

**Issue by ianjuma** [mauricio/postgresql-async#173]
my futures are timing out; is this a worker pool issue? 

```scala
mysqlDbPoolMaxObjects   = 1000
mysqlDbPoolMaxIdle      = 100
mysqlDbPoolMaxQueueSize = 10000
```

I also have set mysql to accept more connections. MySQL's time-out is also big enough. Is this related to issue [#73](https://github.com/mauricio/postgresql-async/issues/73)

```scala
10:00:37 ERROR[t-dispatcher-15] [c.a.m.h.HydraQueueWorker ] - Error while fetching results: java.util.concurrent.TimeoutException: Futures timed out after [5 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:107)
	at com.github.mauricio.async.db.mysql.pool.MySQLConnectionFactory.create(MySQLConnectionFactory.scala:53)
	at com.github.mauricio.async.db.mysql.pool.MySQLConnectionFactory.create(MySQLConnectionFactory.scala:40)
	at com.github.mauricio.async.db.pool.SingleThreadedAsyncObjectPool.com$github$mauricio$async$db$pool$SingleThreadedAsyncObjectPool$$createOrReturnItem(SingleThreadedAsyncObjectPool.scala:201)
	at com.github.mauricio.async.db.pool.SingleThreadedAsyncObjectPool$$anonfun$checkout$1.apply$mcV$sp(SingleThreadedAsyncObjectPool.scala:185)
	at com.github.mauricio.async.db.util.Worker$$anon$1.run(Worker.scala:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

on scala 2.10 and ver 0.2.6

I believe this is in line with a failure to establish a connection. Does having a huge pool help with this?

I tried reducing the queue throughput for this, some futures time-out.

**Comment by ianjuma** [comment]
```scala
13:02:53 ERROR[t-dispatcher-13] [c.a.m.h.HydraQueueWorker ] - Error while fetching results: java.util.concurrent.TimeoutException: Futures timed out after [5 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:107)
	at com.github.mauricio.async.db.mysql.pool.MySQLConnectionFactory.create(MySQLConnectionFactory.scala:52)
	at com.github.mauricio.async.db.mysql.pool.MySQLConnectionFactory.create(MySQLConnectionFactory.scala:39)
	at com.github.mauricio.async.db.pool.SingleThreadedAsyncObjectPool.com$github$mauricio$async$db$pool$SingleThreadedAsyncObjectPool$$createOrReturnItem(SingleThreadedAsyncObjectPool.scala:201)
	at com.github.mauricio.async.db.pool.SingleThreadedAsyncObjectPool$$anonfun$checkout$1.apply$mcV$sp(SingleThreadedAsyncObjectPool.scala:185)
	at com.github.mauricio.async.db.util.Worker$$anon$1.run(Worker.scala:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


```

**Comment by mikx** [comment]
I'm having the similar/related issues, the db requests usually take around 30-60 ms, but once in a while  it would fail because the 5000 ms timeout is reached.

**Comment by lielran** [comment]
we have a similar issue using Postgres 9.6.3
