### ISSUE TITLE
Example with Postgres json column type throws exception

### ISSUE THREAD

**Issue by mcgsoftware** [mauricio/postgresql-async#74]
Not sure how to use json column types, do you have a working test that uses them?  I get the stack trace: 

Caused by: com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Position -> 57, Line -> 510, Hint -> You will need to rewrite or cast the expression., File -> parse_target.c, SQLSTATE -> 42804, Routine -> transformAssignedExpr, Message -> column "addresses" is of type json but expression is of type character varying, Severity -> ERROR))
    at com.github.mauricio.async.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.scala:165) ~[postgresql-async_2.10-0.2.10.jar:0.2.10]
    at com.github.mauricio.async.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.scala:151) ~[postgresql-async_2.10-0.2.10.jar:0.2.10]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:103) ~[netty-all-4.0.12.Final.jar:na]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338) ~[netty-all-4.0.12.Final.jar:na]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324) ~[netty-all-4.0.12.Final.jar:na]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:153) ~[netty-all-4.0.12.Final.jar:na]

---

create table people
 (
  id bigserial primary key,
  name varchar(256),
  addresses json,
  phones json
);

case class People ( id : Option[Long], name : String, addresses :String, phones : String)

object PeopleServiceSql {
  val Insert = "INSERT INTO people (name, addresses, phones) VALUES (?,?,?) RETURNING id"
  val Update = "UPDATE people SET name = ?, addresses = ?, phones = ? WHERE id = ?"
}

class PeopleService(pooledConn: Connection) {

  def crupdate(m: People): Future[People] = {

```
m.id match {
  case Some(id) => pooledConn.sendPreparedStatement(Update, Array(m.name, m.addresses, m.phones, id)).map {
    queryResult => m
  }
  case None => pooledConn.sendPreparedStatement(Insert, Array(m.name, m.addresses, m.phones)).map {
    queryResult => new People(Some(queryResult.rows.get(0)("id").asInstanceOf[Long]),
      m.name, m.addresses, m.phones)
  }
}
```

  }
}

 def add = Action { implicit request =>

```
val toInsert = People(id = None, name = "Sabrina Howitzer",
  addresses = (
    """
      [ {"Home" : {"city" : "Tahoe", "state" : "CA"}} ]
    """.trim),
  phones = (
    """
      [ "925-575-0415", "916-321-2233" ]
    """.trim)
)

AsyncResult {
  Services.peopleService.crupdate(toInsert).map { p =>
    Ok("person inserted: " + p.toString)
  }
}
```

  }

**Comment by divijan** [comment]
Does it support inserting strings into JSONB fields?
